# Generated by Django 5.0.3 on 2024-04-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('userId', models.TextField(null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='BookPicture',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('bookId', models.TextField(primary_key=True, serialize=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'book_image',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('userId', models.TextField(null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'complaints_files',
            },
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('userId', models.TextField(primary_key=True, serialize=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile_image',
            },
        ),
        migrations.CreateModel(
            name='TeacherPicture',
            fields=[
                ('image', models.ImageField(upload_to='')),
                ('userId', models.TextField(primary_key=True, serialize=False)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'teacher_image',
            },
        ),
    ]
